### ISSUE TITLE
Weapon panel icons

### ISSUE THREAD

**Issue by RamseyKal** [heatray/WUMPatch#2]
Hi and thank you for this patch. I'm using the Shaders and patch.ini. The rest I don't need, apart from "Fixed aimers, melee hit, worm select". I would like to use that but without the "Changed weapon panel icons" since I prefer seeing the full icon.
Is it possible to separate those 2? If I could open and edit that Bundl09.xom file, I would attempt to do so.

**Comment by heatray** [comment]
you can import original textures with XomView
