### ISSUE TITLE
FPS Drops

### ISSUE THREAD

**Issue by BlackShadow** [heatray/WUMPatch#4]
FPS Drops still happening randomly. Drops from 144 to 110-120.

Specs:

RTX 2080Ti - i9-9900K - 32GB RAM
OS: Win11 22H2

Game Settings: 

Res: 1080p
Shadow Res: 4096
AA: FXAA

**Comment by heatray** [comment]
game is not quite optimized
it has nothing to do with me

**Comment by BlackShadow** [comment]
Can you do further optimizations?

**Comment by heatray** [comment]
as it turns out, can't promise anything
