### ISSUE TITLE
Force HDR

### ISSUE THREAD

**Issue by Vladjaye** [heatray/WUMPatch#9]
When launching on desktop. it forces HDR off on monitor. Not that the game has HDR, but I keep HDR mode of monitor for higher overall brightness (in nits) of screen. Is there any way to disable forced HDR off?

**Comment by heatray** [comment]
idk, launch game in windowed mode

**Comment by heatray** [comment]
do you mean `FrameInterval` option?

**Comment by Vladjaye** [comment]
> do you mean `FrameInterval` option?

yes. :)

**Comment by heatray** [comment]
It is recommended to always set 0.
This makes FPS unlimited and allows to bypass game's frame limiter, which [causes FPS drops](https://steamcommunity.com/app/70600/discussions/2/3182362324988063587/) on modern Windows
